# Generated by Django 5.0.6 on 2024-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product.jpeg', upload_to='images'),
            preserve_default=False,
        ),
    ]
